use_frameworks!

target 'RxPusherSwift_Example' do
  pod 'RxPusherSwift', :path => '../'

  target 'RxPusherSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end